- id: doi:10.1111/jfb.14779
  tags:
      - Reproduction
  extra-links:
    - type: pdf
      link: images/koenigandgallant2021.pdf

- id: doi:10.1111/evo.13953
  tags:
      - Signal Evolution
  extra-links:
    - type: pdf
      link: images/picqetal2020.pdf

- id: doi:10.1242/jeb.213447
  tags:
      - Review
  extra-links:
    - type: pdf
      link: images/gallant_and_oconnell_2020.pdf

- id: doi:10.1186/s12862-019-1572-3
  tags:
      - Transcriptome
      - Signal Evolution
  extra-links:
    - type: pdf
      link: images/losilla_et_al_2020.pdf

- id: doi:10.1016/j.cub.2018.05.012
  tags:
    - Signal Evolution
  extra-links:
    - type: pdf
      link: images/immani_et_al_2019.pdf

- id: doi:10.3791/60253
  tags:
      - CRISPR
      - Protocol
  extra-links:
    - type: pdf
      link: images/constantinou_etal_2019.pdf

- id: doi:10.1093/gbe/evx265
  tags:
      - Genome
  extra-links:
    - type: pdf
      link: images/gallant_et_al_2017.pdf

- id: doi:10.1016/j.jphysparis.2016.10.003
  tags:
      - Review
  extra-links:
    - type: pdf
      link: images/pitchers_et_al_2016.pdf

- id: doi:10.1186/s12864-015-1288-8
  tags:
      - Genome
      - Transcriptome
  extra-links:
    - type: pdf
      link: images/traeger_et_al_2015.pdf

- id: doi:10.1038/ncomms5817
  extra-links:
  - type: journal
    text: MSU Today
    link: http://msutoday.msu.edu/news/2014/a-single-evolutionary-road-may-lead-to-rome/
  tags:
      - Transcriptome
      - Genome
  extra-links:
    - type: pdf
      link: images/gallant_et_al_2014.pdf

- id: doi:10.1126/science.1254432
  image: images/best_eel_color_corrected_reduced.tif
  extra-links:
    - type: journal
      text: NPR
      link: http://www.npr.org/2014/06/26/325246710/a-shocking-fish-tale-surprises-evolutionary-biologists
    - type: journal
      link: http://www.wired.com/2014/06/electric-fish-convergent-evolution
      text: Wired
    - type: journal
      link: http://newswatch.nationalgeographic.com/2014/06/26/the-shocking-truth-about-electric-animals
      text: National Geographic
    - type: journal
      link: http://www.reuters.com/article/2014/06/26/us-science-fish-idUSKBN0F12UW20140626
      text: Reuters
    - type: journal
      link: http://msutoday.msu.edu/news/2014/sequencing-electric-eel-genome-unlocks-shocking-secrets/
      text: MSU Today
    - type: journal
      link: http://www.agenciasinc.es/Noticias/La-evolucion-de-los-peces-electricos-sorprende-a-los-cientificos
      text: CINA
    - type: pdf
      link: images/gallantetal2014.pdf

  tags:
      - Genome
      - Transcriptome
      - Evo-Devo

- id: doi:10.1016/j.celrep.2013.09.042
  image: images/S2211124713X00166_covhighres.jpg
  extra-links:
    - type: journal
      text: The Economist
      link: http://www.economist.com/news/science-and-technology/21588840-how-species-separate-still-mysterious-lepidoptera-make-things
    - type: journal
      text: LA Times
      link: http://www.latimes.com/science/sciencenow/la-sci-sn-butterflies-evolution-20131030,0,4630140.story#axzz2jKDjncAY)
    - type: journal
      text: Science Magazine
      link: (http://news.sciencemag.org/biology/2013/10/scienceshot-butterfly-study-shows-genomes-change-bits-and-pieces-first)
    - type: pdf
      link: images/kronforstetal2013.pdf
  tags:
      - Genome
      - Transcriptome

- id: doi:10.3109/01677063.2013.799670
  tags:
    - Review
    - Evo-Devo
  extra-links:
    - type: pdf
      link: images/carlson_and_gallant_2013.pdf

- id: doi:10.1242/jeb.063222
  tags:
    - Evo-Devo
  extra-links:
    - type: pdf
      link: images/gallant_etal_2012.pdf

- id: doi:10.1007/s00359-011-0643-8
  tags:
    - Signal Evolution
  extra-links:
    - type: pdf
      link: images/gallant_etal_2011.pdf
